// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ai.preset": string;
      "ai.format": string;
      "ai.baseUrl": string;
      "ai.apiKey": string;
      "ai.model": string;
      "ai.temperature": number;
      "ai.maxTokens": number;
      "ai.profiles": string;
      "ai.activeProfileId": string;
      "ai.customPrompts": string;
      "selectionTranslate.enabled": boolean;
      "selectionTranslate.automatic": boolean;
      "selectionTranslate.provider": string;
      "selectionTranslate.aiProfileId": string;
      "selectionTranslate.sourceLang": string;
      "selectionTranslate.targetLang": string;
      "selectionTranslate.deeplPlan": string;
      "selectionTranslate.deeplKey": string;
      "selectionTranslate.baiduAppId": string;
      "selectionTranslate.baiduKey": string;
      "selectionTranslate.historyLimit": number;
      "selectionTranslate.historyMaxMB": number;
      "selectionTranslate.comparisonEnabled": boolean;
      "selectionTranslate.comparisonTargets": string;
      "selectionTranslate.lengthRulesEnabled": boolean;
      "selectionTranslate.rulesConfigured": boolean;
      "selectionTranslate.lengthRules": string;
      "translate.envSource": string;
      "translate.uvPath": string;
      "translate.bundlePath": string;
      "translate.engine": string;
      "translate.outputs": string;
      "translate.langOut": string;
      "translate.langIn": string;
      "translate.service": string;
      "translate.threads": number;
      "translate.serverUrl": string;
    };
  }
}
